import Pagination from '@/components/Pagination';
import Table from '@/components/Table';
import { createColumnHelper, getCoreRowModel, useReactTable } from '@tanstack/react-table';
import { Card, Col, Form } from 'react-bootstrap';

const OrderStatusList = () => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const columnHelper = createColumnHelper<any>();
  const columns = [
    columnHelper.accessor('OrderName', {
      header: 'Order Name',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('CustomerName', {
      header: 'Customer Name',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('Complete', {
      header: 'Order Status',
      cell: () => <span>{'Completed'}</span>,
    }),
    columnHelper.accessor('ClientName', {
      header: 'Client Name',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('DriverName', {
      header: 'Driver Name',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('StatusName', {
      header: 'Status Name',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('DEP_TIME', {
      header: 'Departure Time',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.display({
      id: 'Create Order Instruction',
      header: () => <span>Action</span>,
      cell: () => (
        <span className="d-block text-center cursor-pointer">
          <i className="fas fa-eye me-1"></i>
        </span>
      ),
    }),
  ];

  const useReactTableReturn = useReactTable({
    data: OrderStatusRecord,
    columns: columns,
    getCoreRowModel: getCoreRowModel(),
  });
  return (
    <Col sm={12} className="col-12">
      <Card className="card-primary">
        <Card.Header>
          <h4 className="card-title">Order Status List</h4>
          <div className="d-flex justify-content-start mt-4">
            <Form.Control className="form-control w-25 mb-0" placeholder="Search..." />
          </div>
        </Card.Header>
        <Card.Body className="pt-0">
          <Table useReactTableReturn={useReactTableReturn} />
          <Pagination />
        </Card.Body>
      </Card>
    </Col>
  );
};

export default OrderStatusList;

const OrderStatusRecord = [
  {
    OrderStatusId: 35245,
    OrderId: 'f8eebe6e-32fa-4c9f-b465-70bb209b4960',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: '',
    CustomerName: 'Leyton',
    ROUTENAME: 'Run-0004',
    Email: '',
    mobile: '',
    DriverName: 'Leon',
    CreatedOnUTC: '/Date(1687663117243)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35246,
    OrderId: '8d73bcab-f430-4b7f-8e37-1e88f8206295',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'OOS006',
    CustomerName: 'Jubilee Place AM and PM delivery',
    ROUTENAME: 'Run-0004',
    Email: '',
    mobile: '',
    DriverName: 'Leon',
    CreatedOnUTC: '/Date(1687663117243)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35247,
    OrderId: '29940f3d-5154-4762-8bb4-cdeb5d16c384',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'OOS014',
    CustomerName: 'More London AM Delivery',
    ROUTENAME: 'Run-0004',
    Email: 'MoreLondon@oleandsteen.co.uk',
    mobile: '',
    DriverName: 'Leon',
    CreatedOnUTC: '/Date(1687663117243)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35248,
    OrderId: '852dad7a-b911-43a0-85a0-f322e54701eb',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: '',
    CustomerName: 'Leyton',
    ROUTENAME: 'Run-0004',
    Email: '',
    mobile: '',
    DriverName: 'Leon',
    CreatedOnUTC: '/Date(1687663117243)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35241,
    OrderId: 'edd7e1f6-a2a6-484d-bed3-654a75ed8875',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: '',
    CustomerName: 'Leyton',
    ROUTENAME: 'Run-0005',
    Email: '',
    mobile: '',
    DriverName: 'Subramaniam',
    CreatedOnUTC: '/Date(1687663069553)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35242,
    OrderId: '4c6fe515-3638-4147-a5b4-13e7751a5b18',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'OOS008',
    CustomerName: 'Canary Wharf AM and PM Delivery',
    ROUTENAME: 'Run-0005',
    Email: 'canarywharf@oleandsteen.co.uk',
    mobile: '',
    DriverName: 'Subramaniam',
    CreatedOnUTC: '/Date(1687663069553)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35243,
    OrderId: '52ce9e41-fff7-4224-9c6e-639cbfad78ce',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'ORD-000045',
    CustomerName: 'Greenwich',
    ROUTENAME: 'Run-0005',
    Email: '',
    mobile: '',
    DriverName: 'Subramaniam',
    CreatedOnUTC: '/Date(1687663069553)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35244,
    OrderId: '4ea1c1ec-d551-446e-87f1-dadcdd37601f',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: '',
    CustomerName: 'Leyton',
    ROUTENAME: 'Run-0005',
    Email: '',
    mobile: '',
    DriverName: 'Subramaniam',
    CreatedOnUTC: '/Date(1687663069553)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35237,
    OrderId: '2b8b6406-33cd-4e3b-933e-a65865de4da6',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: '',
    CustomerName: 'Leyton',
    ROUTENAME: 'Run-0009',
    Email: '',
    mobile: '',
    DriverName: 'Sam',
    CreatedOnUTC: '/Date(1687662327293)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35238,
    OrderId: '47ec20be-b817-41c1-a55d-9e84d84e7830',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'OOS007',
    CustomerName: 'Eccleston Place AM Delivery',
    ROUTENAME: 'Run-0009',
    Email: 'Ecclestonplace@oleandsteen.co.uk',
    mobile: '',
    DriverName: 'Sam',
    CreatedOnUTC: '/Date(1687662327293)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35239,
    OrderId: 'd5155d34-49ff-41e8-8430-26039138349d',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'OOS010',
    CustomerName: 'Clapham (Northcote) AM and PM Delivery',
    ROUTENAME: 'Run-0009',
    Email: 'NorthcoteRoad@oleandsteen.co.uk',
    mobile: '',
    DriverName: 'Sam',
    CreatedOnUTC: '/Date(1687662327293)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35240,
    OrderId: 'a2ee466d-bb18-4a73-8d13-fa999a49b243',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: '',
    CustomerName: 'Leyton',
    ROUTENAME: 'Run-0009',
    Email: '',
    mobile: '',
    DriverName: 'Sam',
    CreatedOnUTC: '/Date(1687662327293)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35229,
    OrderId: '30300175-b792-4932-b89f-215b2cf8c0a7',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: '',
    CustomerName: 'Leyton',
    ROUTENAME: 'Run-0007',
    Email: '',
    mobile: '',
    DriverName: 'Ismail',
    CreatedOnUTC: '/Date(1687662228583)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35230,
    OrderId: '285fc7ca-6cd8-41ac-9759-c5581fcaaea7',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'OOS026',
    CustomerName: 'Wigmore Street AM Delivery',
    ROUTENAME: 'Run-0007',
    Email: 'wigmore@oleandsteen.co.uk',
    mobile: '',
    DriverName: 'Ismail',
    CreatedOnUTC: '/Date(1687662228583)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35231,
    OrderId: 'b29f4eae-6987-47f9-b80a-92ff7a3ef303',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'OOS023',
    CustomerName: 'Tottenham CR AM Delivery',
    ROUTENAME: 'Run-0007',
    Email: 'tottenhamcourtroad@oleandsteen.co.uk',
    mobile: '',
    DriverName: 'Ismail',
    CreatedOnUTC: '/Date(1687662228583)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35232,
    OrderId: 'cc3179c8-5127-46e0-bac8-87c7d2fc22b6',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'OOS017',
    CustomerName: 'Oxford Circus AM Delivery',
    ROUTENAME: 'Run-0007',
    Email: 'oxfordcircus@oleandsteen.co.uk',
    mobile: '',
    DriverName: 'Ismail',
    CreatedOnUTC: '/Date(1687662228583)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35233,
    OrderId: 'fd8f5e79-9c38-4aa7-af9b-be0cc834121e',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'Customer Service',
    CustomerName: '',
    ROUTENAME: 'Run-0007',
    Email: '',
    mobile: '',
    DriverName: 'Ismail',
    CreatedOnUTC: '/Date(1687662228583)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: true,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
  {
    OrderStatusId: 35234,
    OrderId: 'cd22b02b-94b5-49e3-adac-9d6bacc57acc',
    RouteId: '00000000-0000-0000-0000-000000000000',
    StatusName: 'Order Delivered',
    SignatureImage: null,
    ProofOfDeliveryImage: null,
    ProofOfDeliveryImage2: null,
    DeliveryRecipient: null,
    TypeOfOrder: null,
    IsItemMissing: false,
    MissingItemRemark: null,
    Reasons: null,
    Temperature: null,
    Chilled: 0,
    Frozen: 0,
    Hot: 0,
    OrderName: 'OOS040',
    CustomerName: 'Tottenham CR - Collect Empties',
    ROUTENAME: 'Run-0007',
    Email: 'tottenhamcourtroad@oleandsteen.co.uk',
    mobile: '',
    DriverName: 'Ismail',
    CreatedOnUTC: '/Date(1687662228583)/',
    Latitude: null,
    Longitude: null,
    DriverPerformance: null,
    Review: null,
    Address: null,
    Rating: 0,
    Time: null,
    Comments: null,
    Ambient: null,
    CollectionPersonName: null,
    IsWaitingTime: false,
    TempratureRange: null,
    ClientName: '',
    ProfileName: 'Ole and Steen Sat-Sun 25 06 23',
    IsLateDelivery: false,
    ReasonForLateDelivery: null,
    TrolliesDelivered: 0,
    TrolliesCollected: 0,
  },
];
