import React from 'react';
import { createColumnHelper, useReactTable, getCoreRowModel } from '@tanstack/react-table';
import Table from '@/components/Table';
import Pagination from '@/components/Pagination';
import { useDialogState } from '@/hooks/useDialogState';
import Dialog from '@/components/Modal';
import Button from '@/components/Button';
import { useNavigate } from 'react-router-dom';

const RouteAssignmentList = () => {
  const navigate = useNavigate();
  const { isOpen, setCloseDialog, setOpenDialog } = useDialogState();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const columnHelper = createColumnHelper<any>();
  const columns = [
    columnHelper.accessor('FirstName', {
      header: 'Driver Name',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('ClientGroupName', {
      header: 'Client Group',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('RouteName', {
      header: 'Route Name',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('RouteStart', {
      header: 'Route Start',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('RouteDate', {
      header: 'Route Date',
      cell: ({ getValue }) => <span>{getValue() || ''}</span>,
    }),
    columnHelper.accessor('AcceptByDriver', {
      header: 'Accepted',
      cell: ({ getValue }) => (
        <span className={`${getValue() ? 'text-success' : 'text-danger'}`}>{getValue() ? 'Yes' : 'No'}</span>
      ),
    }),
    columnHelper.accessor('ProfileName', {
      header: 'Profile',
      cell: ({ getValue }) => <span>{getValue() || ''}</span>,
    }),
    columnHelper.accessor('CancelledByAdmin', {
      header: 'Cancelled',
      cell: ({ getValue }) => (
        <span className={`${getValue() ? 'text-success' : 'text-danger'}`}>{getValue() ? 'Yes' : 'No'}</span>
      ),
    }),
    columnHelper.accessor('RouteStartTime', {
      header: 'Route Start Time',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.accessor('RouteEndTime', {
      header: 'Route End Time',
      cell: ({ getValue }) => <span>{getValue()}</span>,
    }),
    columnHelper.display({
      id: 'Create Order Instruction',
      header: () => <span>Action</span>,
      cell: () => (
        <span className="d-block text-center cursor-pointer text-primary">
          <i className="fas fa-eye me-1" onClick={() => navigate('/route-assignment-list/assigned-orders-list')}></i>
          <i className="far fa-trash-alt" onClick={setOpenDialog}></i>
        </span>
      ),
    }),
  ];

  const useReactTableReturn = useReactTable({
    data: RouteAssignmentRecord,
    columns: columns,
    getCoreRowModel: getCoreRowModel(),
  });
  return (
    <React.Fragment>
      <Table useReactTableReturn={useReactTableReturn} />
      <Pagination />
      <Dialog title="Delete Assigned Route" show={isOpen} handleClose={setCloseDialog}>
        <div>
          <p className="tx-14 tx-medium mg-b-20">Are you sure you want to delete this item?</p>
          <div className="d-flex justify-content-end">
            <Button
              btnType="btn-outline-danger"
              btnSize="btn-sm"
              className="pd-x-25 me-2"
              type="button"
              onClick={setCloseDialog}
            >
              Cancel
            </Button>
            <Button btnType="btn-primary" btnSize="btn-sm" className="pd-x-25" type="button">
              Confirm
            </Button>
          </div>
        </div>
      </Dialog>
    </React.Fragment>
  );
};

export default RouteAssignmentList;

const RouteAssignmentRecord = [
  {
    LinkId: 4896,
    JobId: 0,
    JobName: null,
    RouteId: '1bc88fc5-c2b8-4526-8ef2-3d7ca8f3286d',
    DriverId: 169,
    RouteName: 'Run-0009',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Sam',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4892,
    JobId: 0,
    JobName: null,
    RouteId: '784f8bdb-0174-4dcf-8db4-9595b1568ec7',
    DriverId: 164,
    RouteName: 'Run-0005',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Saim',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4889,
    JobId: 0,
    JobName: null,
    RouteId: 'a32a4f86-c566-4dbf-8559-8cb1566b4845',
    DriverId: 183,
    RouteName: 'Run-0002',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Hamza',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4893,
    JobId: 0,
    JobName: null,
    RouteId: 'ebe4527e-5076-47d5-9f28-efd95e6d6df8',
    DriverId: 135,
    RouteName: 'Run-0006',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Nadeshakumar',
    AcceptByDriver: false,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: true,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4899,
    JobId: 0,
    JobName: null,
    RouteId: 'ebe4527e-5076-47d5-9f28-efd95e6d6df8',
    DriverId: 127,
    RouteName: 'Run-0006',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Subramaniam',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4895,
    JobId: 0,
    JobName: null,
    RouteId: 'f878fa10-ea83-46f3-be00-01ec3edf1fdc',
    DriverId: 203,
    RouteName: 'Run-0008',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Junior',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4888,
    JobId: 0,
    JobName: null,
    RouteId: '6d2a141a-b10e-4aff-9d10-ec3b4e00eb6f',
    DriverId: 138,
    RouteName: 'Run-0001',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Dawid',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '8/7/2023 10:57:17',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4898,
    JobId: 0,
    JobName: null,
    RouteId: 'db89ad38-4447-4863-b2bb-bc74516b5570',
    DriverId: 171,
    RouteName: 'Run-0012',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Ibrahim',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4891,
    JobId: 0,
    JobName: null,
    RouteId: '8dbcf537-6940-42d1-9d3c-79fd5c44f40e',
    DriverId: 167,
    RouteName: 'Run-0004',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Leon',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4894,
    JobId: 0,
    JobName: null,
    RouteId: '8d1d0059-61cb-444e-86cf-013c5649c965',
    DriverId: 158,
    RouteName: 'Run-0007',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Constantine',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4897,
    JobId: 0,
    JobName: null,
    RouteId: '346d0f80-8ad1-4e79-b94b-c30d5e7da72a',
    DriverId: 177,
    RouteName: 'Run-0011',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Leao',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
  {
    LinkId: 4890,
    JobId: 0,
    JobName: null,
    RouteId: 'e4884fe0-5758-4fd0-8dfb-8ed969a6439f',
    DriverId: 175,
    RouteName: 'Run-0003',
    RouteStart: null,
    RouteEnd: null,
    FirstName: 'Telbirth',
    AcceptByDriver: true,
    RouteDate: '8/7/2023',
    LATITUDE: null,
    LONGITUDE: null,
    IsJob: 0,
    StatusId: 0,
    StatusName: null,
    OrderStatusId: 0,
    ProfileName: 'Ole and Steen Sat-Sun 08 07 23',
    CancelledByAdmin: false,
    SelectedPeriod: null,
    AutoAssign: false,
    AutoAssignStartDate: null,
    AutoAssignEndDate: null,
    MatchingText: null,
    RouteStartTime: '8/7/2023 7:45:6',
    RouteEndTime: '',
    ClientGroupName: 'Ole and Steen',
    IsAutoRoute: 0,
  },
];
