import React from 'react';
import { createColumnHelper, useReactTable, getCoreRowModel } from '@tanstack/react-table';
import { useNavigate } from 'react-router-dom';
import Table from '@/components/Table';
import Pagination from '@/components/Pagination';

const CustomerReviewRatingList = () => {
  const navigate = useNavigate();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const columnHelper = createColumnHelper<any>();
  const columns = [
    columnHelper.accessor('ORDER', {
      header: 'Order Name',
      cell: ({ getValue }) => <span>{getValue() || ''}</span>,
    }),
    columnHelper.accessor('Customername', {
      header: 'Customer Name',
      cell: ({ getValue }) => <span>{getValue() || ''}</span>,
    }),
    columnHelper.accessor('RouteName', {
      header: 'Route Name',
      cell: ({ getValue }) => <span>{getValue() || ''}</span>,
    }),
    columnHelper.accessor('DriverName', {
      header: 'Driver Name',
      cell: ({ getValue }) => <span>{getValue() || ''}</span>,
    }),
    columnHelper.accessor('ClientGroupName', {
      header: 'Client Group',
      cell: ({ getValue }) => <span>{getValue() || ''}</span>,
    }),
    columnHelper.accessor('Review', {
      header: 'Customer Review',
      cell: ({ getValue }) => <span>{getValue() || ''}</span>,
    }),
    columnHelper.accessor('CreatedOnUtc', {
      header: 'Addes On',
      cell: ({ getValue }) => <span>{getValue() || ''}</span>,
    }),
    columnHelper.display({
      id: 'Create Order Instruction',
      header: () => <span>Action</span>,
      cell: () => (
        <span className="d-block text-center cursor-pointer text-primary">
          <i
            className="fas fa-eye me-1"
            onClick={() => navigate('/customer-review-and-rating/driver-route-review')}
          ></i>
        </span>
      ),
    }),
  ];

  const useReactTableReturn = useReactTable({
    data: RouteRecord,
    columns: columns,
    getCoreRowModel: getCoreRowModel(),
  });
  return (
    <React.Fragment>
      <Table useReactTableReturn={useReactTableReturn} />
      <Pagination />
    </React.Fragment>
  );
};

export default CustomerReviewRatingList;

const RouteRecord = [
  {
    DeliveryReviewAndRatingId: 54,
    OrderId: 'a2196809-e161-4e56-b449-6a838b2a024f',
    Customername: 'Wigmore Street AM Delivery',
    ORDER: 'OOS026',
    CustomerEmail: 'wigmore@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0007',
    DriverName: 'Pathmanathan Kirushanth',
    VehicleNumber: 'WM19CYA',
    DriverId: 0,
    CustomerId: null,
    Review:
      'Driver only collected blue fridge and left the rest in shop , it is usually this driver who seems to do this on regular basis .',
    DriverPerformance: 'On time delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 3,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1682222784347)/',
  },
  {
    DeliveryReviewAndRatingId: 53,
    OrderId: '02bc0563-0fec-4d42-937f-d57b71e189d1',
    Customername: 'RONTEC RIPPLE',
    ORDER: 'BPRONTECRIPP',
    CustomerEmail: 'tevin@gv-group.co.uk',
    PhoneNumber: null,
    RouteName: 'RUN0001',
    DriverName: 'Arnold Sarfo-Kantanka',
    VehicleNumber: 'NHHHHHG',
    DriverId: 0,
    CustomerId: null,
    Review: null,
    DriverPerformance: 'On time delivery',
    ClientGroupName: null,
    Rating: 5,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1676539626060)/',
  },
  {
    DeliveryReviewAndRatingId: 52,
    OrderId: '71d7ae8d-12c8-4860-a1e6-f84a7cee824b',
    Customername: 'Sample 12',
    ORDER: 'PL13',
    CustomerEmail: 'arnold.sarfo@gmail.com',
    PhoneNumber: null,
    RouteName: 'Run-0001',
    DriverName: 'Arnold Sarfo-Kantanka',
    VehicleNumber: 'JGXSGIJ',
    DriverId: 0,
    CustomerId: null,
    Review: null,
    DriverPerformance: 'Late delivery',
    ClientGroupName: null,
    Rating: 1,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1675773041383)/',
  },
  {
    DeliveryReviewAndRatingId: 39,
    OrderId: 'c48fef5b-b434-4e9e-a611-ac61ff8fb073',
    Customername: 'FINANCIAL OMBUDSMAN',
    ORDER: 'LONDON11',
    CustomerEmail: 'Jon.Fitt@uk.bp.com',
    PhoneNumber: null,
    RouteName: 'Run-0001',
    DriverName: 'Arnold Sarfo-Kantanka',
    VehicleNumber: 'R909CGK',
    DriverId: 0,
    CustomerId: null,
    Review: 'bcncnnc',
    DriverPerformance: 'On time delivery',
    ClientGroupName: null,
    Rating: 3,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1666695272677)/',
  },
  {
    DeliveryReviewAndRatingId: 38,
    OrderId: 'cba9cd83-67e1-4b3b-a80e-9ce5b3b71e60',
    Customername: 'Victoria Nova AM Delivery',
    ORDER: 'OOS024',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0006',
    DriverName: 'Rajasingham Gunapalan',
    VehicleNumber: 'WM19CYA',
    DriverId: 0,
    CustomerId: null,
    Review: 'late delivery when it should be in store by 6.30am at the latest it was again at 7.10am this morning',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 3,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1667026010997)/',
  },
  {
    DeliveryReviewAndRatingId: 37,
    OrderId: 'cb260555-8471-44f7-8963-2fe300a69a00',
    Customername: 'Victoria Nova PM Delivery',
    ORDER: 'OOS041',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0006',
    DriverName: 'Rajasingham Gunapalan',
    VehicleNumber: 'WM19CYA',
    DriverId: 0,
    CustomerId: null,
    Review:
      "it's been every single day this week that the delivery is late, as much as we understand and respect the stressful task each driver must be experiencing , a delayed delivery pushes back all our team for the rest of the morning. if you could please aim to be in store by 6.30am at the latest every day this could be very helpful to us thank you",
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 3,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1667030102873)/',
  },
  {
    DeliveryReviewAndRatingId: 36,
    OrderId: '370c963f-4396-49b8-a9f3-727f755f87a3',
    Customername: 'Victoria Nova PM Delivery',
    ORDER: 'OOS041',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0006',
    DriverName: 'Zakariya Ali',
    VehicleNumber: 'WM19CYA',
    DriverId: 0,
    CustomerId: null,
    Review: 'Eta 06.45',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 4,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1666853802693)/',
  },
  {
    DeliveryReviewAndRatingId: 35,
    OrderId: '25c6e3ec-bdd4-41e7-b41a-a6363f1e90c8',
    Customername: 'Victoria Nova AM Delivery',
    ORDER: 'OOS024',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0006',
    DriverName: 'Zakariya Ali',
    VehicleNumber: 'WM19CYA',
    DriverId: 0,
    CustomerId: null,
    Review: 'ETA 07.05',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 4,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1666682268103)/',
  },
  {
    DeliveryReviewAndRatingId: 34,
    OrderId: '8c9767d3-2824-4215-b3ae-0973a825cb8d',
    Customername: 'Victoria Nova PM Delivery',
    ORDER: 'OOS041',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0006',
    DriverName: 'Zakariya Ali',
    VehicleNumber: 'WM19CYA',
    DriverId: 0,
    CustomerId: null,
    Review: 'ETA 06.47',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 4,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1666597022640)/',
  },
  {
    DeliveryReviewAndRatingId: 33,
    OrderId: 'd2125378-acba-4365-a5ee-73a6f72815ff',
    Customername: 'Canary Wharf AM and PM Delivery',
    ORDER: 'OOS008',
    CustomerEmail: 'canarywharf@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0004',
    DriverName: 'Rajasingham Gunapalan',
    VehicleNumber: 'WM19CXX',
    DriverId: 0,
    CustomerId: null,
    Review: 'Very slow with bringing trolleys in, staff had to rush due to food being brought to store so last minute.',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 5,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1666423277947)/',
  },
  {
    DeliveryReviewAndRatingId: 32,
    OrderId: 'b0dfa26c-772f-44c4-a961-a3d99109598b',
    Customername: 'Victoria Nova AM Delivery',
    ORDER: 'OOS024',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0006',
    DriverName: 'Pathmanathan Kirushanth',
    VehicleNumber: 'WM19CYA',
    DriverId: 0,
    CustomerId: null,
    Review: 'Eta 08.20 instead of 06.30',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 3,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1665814913140)/',
  },
  {
    DeliveryReviewAndRatingId: 31,
    OrderId: '7bc60c30-7665-457a-8d17-9fcee419e3bb',
    Customername: 'Victoria Nova PM Delivery',
    ORDER: 'OOS041',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0008',
    DriverName: 'Nisanthan Nithiyananthan',
    VehicleNumber: 'WM19CXT',
    DriverId: 0,
    CustomerId: null,
    Review: 'eta 07.05',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 4,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1665388357453)/',
  },
  {
    DeliveryReviewAndRatingId: 30,
    OrderId: 'febc7405-6b3a-43ce-8aaa-4934506ad758',
    Customername: 'Victoria Nova PM Delivery',
    ORDER: 'OOS041',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0008',
    DriverName: 'Nadeshakumar Seenithamby',
    VehicleNumber: 'WM19CXT',
    DriverId: 0,
    CustomerId: null,
    Review: 'eta 07.05',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 4,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1665212317843)/',
  },
  {
    DeliveryReviewAndRatingId: 29,
    OrderId: '94266f45-a2e7-4af1-8d9f-d4a0b6a55506',
    Customername: 'Tottenham CR AM Delivery',
    ORDER: 'OOS023',
    CustomerEmail: 'tottenhamcourtroad@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0008',
    DriverName: 'Byron Cambell',
    VehicleNumber: 'YF71DHP',
    DriverId: 0,
    CustomerId: null,
    Review:
      'Cakes not out on the displays, one of the trolley must have been through some accident as pastries dropped levels down, had to bin quite few. Blue fridge left, cakes went over temperature. ',
    DriverPerformance: 'On time delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 1,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1665119496413)/',
  },
  {
    DeliveryReviewAndRatingId: 28,
    OrderId: 'e0843bbd-094d-4646-8379-ab89a2fc46ca',
    Customername: 'Victoria Nova PM Delivery',
    ORDER: 'OOS041',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0008',
    DriverName: 'Nisanthan Nithiyananthan',
    VehicleNumber: 'WM19CXT',
    DriverId: 0,
    CustomerId: null,
    Review: 'delivery arrived 06.40',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 4,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1664866944613)/',
  },
  {
    DeliveryReviewAndRatingId: 27,
    OrderId: 'b194c3c6-f020-4213-88ab-a579e03d2019',
    Customername: 'Leicester Sq AM and PM Delivery',
    ORDER: 'OOS013',
    CustomerEmail: 'leicestersquare@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0009',
    DriverName: 'Dawid Leda',
    VehicleNumber: 'WM19CXU',
    DriverId: 0,
    CustomerId: null,
    Review:
      'My delivery used to come by 7.10am but since this new system always coming late. Today 7.30am and yesterday 7.40am, what give my team 20min only to run around like crazy to try to set up everything by 8am what its stressful. Can you look into this and get my deliveries earlier as used to be. ',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 1,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1664864957517)/',
  },
  {
    DeliveryReviewAndRatingId: 26,
    OrderId: '71f1e41b-c917-4527-91ea-42660e750351',
    Customername: 'Victoria Nova PM Delivery',
    ORDER: 'OOS041',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0008',
    DriverName: 'Nisanthan Nithiyananthan',
    VehicleNumber: 'WM19CXT',
    DriverId: 0,
    CustomerId: null,
    Review: '07:06 delivery arrived',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 3,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1664781956393)/',
  },
  {
    DeliveryReviewAndRatingId: 25,
    OrderId: '00fd3336-99eb-4102-8eba-83e3294e9f4f',
    Customername: 'Victoria Nova PM Delivery',
    ORDER: 'OOS041',
    CustomerEmail: 'victorianova@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0009',
    DriverName: 'Nisanthan Nithiyananthan',
    VehicleNumber: 'WM19CXT',
    DriverId: 0,
    CustomerId: null,
    Review: 'Driver was in a rush, felt like under pressure.',
    DriverPerformance: 'Late delivery',
    ClientGroupName: 'Ole and Steen',
    Rating: 3,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1664699968413)/',
  },
  {
    DeliveryReviewAndRatingId: 24,
    OrderId: '5aff40a3-1122-4c98-b635-34d99bdc8dcf',
    Customername: 'Windsor AM and PM Delivery',
    ORDER: 'OOS027',
    CustomerEmail: 'Windsor@oleandsteen.co.uk',
    PhoneNumber: null,
    RouteName: 'Run-0005',
    DriverName: 'Byron Cambell',
    VehicleNumber: 'YF71DHP',
    DriverId: 0,
    CustomerId: null,
    Review: null,
    DriverPerformance: 'Delivered in full',
    ClientGroupName: 'Ole and Steen',
    Rating: 2,
    CreatedOnUtc: '24/4/2023',
    DateOfDelivery: '/Date(1664603291820)/',
  },
];
